# Use root/example as user/password credentials
# https://hub.docker.com/_/mysql/
version: '3.1'

services:
  db:
    image: mysql:8.0.21
    container_name: mysql-8021-33061
    restart: always
    command: 
      --default-authentication-plugin=mysql_native_password
      --lower-case-table-names=1
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
    volumes:
      - /Users/panxiaoan/work/docker/mysql-8.0.21-33061/data:/var/lib/mysql:rw # 数据
      - /Users/panxiaoan/work/docker/mysql-8.0.21-33061/conf:/etc/mysql:rw # 配置
      - /Users/panxiaoan/work/docker/mysql-8.0.21-33061/conf:/etc/mysql/my.cnf:rw
      - /Users/panxiaoan/work/docker/mysql-8.0.21-33061/mysql-files:/var/lib/mysql-files:rw
      # - /etc/localtime:/etc/localtime:ro
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 33061:3306
    deploy:
      resources:
        limits:
          memory: 2g
      restart_policy:
        condition: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "512k"
        max-file: "5"

  # 简易网页客户端 https://www.adminer.org
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080