# https://hub.docker.com/_/influxdb?tab=tags
version: '3'

services:
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    hostname: influxdb
    restart: always
    ports:
      - 9161:8086 # Grafana select data from influxdb
      - 9162:2003 # JMeter update data
    environment:
        INFLUXDB_DB: jmeterdb
        INFLUXDB_ADMIN_USER: admin
        INFLUXDB_ADMIN_PASSWORD: admin
        INFLUXDB_USER: user
        INFLUXDB_USER_PASSWORD: user
        INFLUXDB_DATA_QUERY_LOG_ENABLED: "false"
        INFLUXDB_GRAPHITE_ENABLED: "true"
    volumes:
      - ./volumes/conf/influxdb.conf:/etc/influxdb/influxdb.conf
      - ./volumes/data:/var/lib/influxdb
    networks:
      - net_db
networks:
  net_db:
    driver: bridge